# Generated by Django 4.1.7 on 2023-03-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_staffdetail_patentdetail_doctordetail_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patentdetail',
            name='patent_age',
            field=models.IntegerField(),
        ),
    ]
